[package]
name = "cities-csv"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8.1", features = ["runtime-tokio", "sqlite"]}
tokio = { version = "1.0", features = ["full"]}
